### PR TITLE
Panic fix

### PR DESCRIPTION
**Pull request by twuerker**
## Overview 
Trying to fix the panic errors we've been seeing from `config.Load`. This PR gets rid of using `config.Load` to validate the configurations.

### Old Flow
1. Validate the new configuration with `config.Load`. If any validation errors return the failure
1. Write the updated configuration in the prom config file
1. Call Reload on Prometheus

### New Flow
1. Get and save the original configuration from prometheus
1. Write the updated configuration in the prom config file
1. Call Reload on Prometheus, which will return any validation errors, which the handler will forward in the response
1. If any validation errors, call defer functions that will write the original configuration in the prom config file

## Additional Changes
- Updates to the docker-compose file, getting it to work and trying to mimic client environments closer, but I still wasn't able to reproduce the panic errors
- Lean into using the structured logger from https://github.com/go-kit/log instead of using `log`. This is what prometheus is using, and we should probably be using a structured logger as well

### CODE REVIEW

**Comment by twuerker** [comment]
Can we skip this rule? In `WriteFile`, the path for the file is from configuration, and the content is from the user request body, which it needs to be.
image

**Review by mattamizer — APPROVED** [review]

**Comment by mattamizer** [comment]
I think so? I'm not sure how else we'd handle that

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mattamizer** [comment]
> Can we skip this rule? In `WriteFile`, the path for the file is from configuration, and the content is from the user request body, which it needs to be. image

We _could_ implement the validation checks that the tool suggests but in this context aren't *we* the user? That file is a fixed path provided by us and isn't user modifiable if I remember correctly.

**Comment by twuerker** [comment]
Yeah, I looking trying to look through some docs on this, and I think the path forward to to merge this and let the code scanning be. Then, we have the option to "dismiss" that alert. https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing-or-deleting-alerts

Trying to see if there's a way to add a code scanning annotation directly in the code itself...

**Comment by dgrizzanti** [comment]
For what it's worth, I added the CodeQL stuff on a whim as I thought it would be useful. If it's causing pain, then I'd say it's definitely fine to merge and address/dismiss when convenient.

**Comment by twuerker** [comment]
Yeah, I'm going to merge and then I think we can dismiss that alert in the Security tab, or have a discussion about dismissing it there.

**Pull request merged**
